#!/usr/bin/env bash
# ============================================================
# diff-pkglist.sh
# Description : Compares two package snapshots (generated by
#               export-pkglist.sh) or a snapshot against the
#               current system. Reports added, removed,
#               upgraded and downgraded packages.
# Dependencies: pacman, vercmp, expac (optional)
# Compatibility: CachyOS, Arch Linux
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
# shellcheck source=../utils/common.sh
source "${SCRIPT_DIR}/../utils/common.sh"

SHOW_UNCHANGED=false
FILTER=""        # "aur" | "official" | "" (all)
SUMMARY_ONLY=false

# --- Parse args ---
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --unchanged|-u)
                SHOW_UNCHANGED=true; shift ;;
            --aur-only)
                FILTER="aur"; shift ;;
            --official-only)
                FILTER="official"; shift ;;
            --summary|-s)
                SUMMARY_ONLY=true; shift ;;
            --help|-h)
                echo "Usage: $(basename "$0") FILE_A [FILE_B]"
                echo ""
                echo "  FILE_A          Snapshot file (from export-pkglist.sh)"
                echo "  FILE_B          Second snapshot, or omit to compare against current system"
                echo ""
                echo "  --unchanged     Also show packages with no version change"
                echo "  --aur-only      Only compare AUR packages"
                echo "  --official-only Only compare official packages"
                echo "  --summary       Print counts only, no per-package listing"
                exit 0 ;;
            -*) warn "Unknown argument: $1"; shift ;;
            *)  # Positional args: collect in order
                if [[ -z "${FILE_A:-}" ]]; then FILE_A="$1"
                elif [[ -z "${FILE_B:-}" ]]; then FILE_B="$1"
                fi
                shift ;;
        esac
    done
}

# --- Detect snapshot format ---
detect_format() {
    local file="$1"
    local first_nonblank
    first_nonblank=$(grep -m1 '.' "$file" 2>/dev/null)
    if [[ "$first_nonblank" == "{"* ]]; then
        echo "json"
    else
        echo "text"
    fi
}

# --- Parse snapshot into TSV: name TAB version TAB repo ---
parse_snapshot() {
    local file="$1"
    local fmt
    fmt=$(detect_format "$file")

    if [[ "$fmt" == "json" ]]; then
        if command -v jq &>/dev/null; then
            jq -r '(.official[],.aur[]) | [.name, .version, .repo] | @tsv' "$file" 2>/dev/null
        else
            # Fallback: naive grep-based parse for simple JSON.
            # Process substitution avoids predictable /tmp temp files.
            paste \
                <(grep -oP '"name":\s*"\K[^"]+'    "$file") \
                <(grep -oP '"version":\s*"\K[^"]+' "$file") \
                <(grep -oP '"repo":\s*"\K[^"]+'    "$file")
        fi
    else
        # Text format: skip comment lines (#), section headers (##, ───),
        # column header lines (NAME …) and blank lines.
        # Data lines: first token = name, second = version, optional third = repo
        grep -v '^\s*#\|^##\|^──\|^\s*$\|^NAME\s' "$file" \
            | awk '{
                if (NF >= 2) {
                    repo = (NF >= 3) ? $3 : "unknown"
                    printf "%s\t%s\t%s\n", $1, $2, repo
                }
            }'
    fi
}

# --- Get current system packages as TSV ---
get_current_pkgs() {
    if command -v expac &>/dev/null; then
        local sync_data query_data
        sync_data=$(expac '%n\t%r' --sync 2>/dev/null)
        query_data=$(expac '%n\t%v' --query 2>/dev/null)

        awk -F'\t' '
            NR==FNR { repo[$1]=$2; next }
            { r = ($1 in repo) ? repo[$1] : "aur"
              printf "%s\t%s\t%s\n", $1, $2, r }
        ' <(echo "$sync_data") <(echo "$query_data")
    else
        pacman -Qn 2>/dev/null | awk '{printf "%s\t%s\tofficial\n", $1, $2}'
        pacman -Qm 2>/dev/null | awk '{printf "%s\t%s\taur\n", $1, $2}'
    fi
}

# --- Load TSV data into associative arrays ---
# Populates: names_arr (name→version) and repos_arr (name→repo)
load_pkgs() {
    local tsv="$1"
    local -n names_ref="$2"
    local -n repos_ref="$3"

    while IFS=$'\t' read -r name version repo; do
        [[ -z "$name" ]] && continue
        # Apply filter
        if [[ "$FILTER" == "aur" && "$repo" != "aur" ]]; then continue; fi
        if [[ "$FILTER" == "official" && "$repo" == "aur" ]]; then continue; fi
        names_ref["$name"]="$version"
        repos_ref["$name"]="$repo"
    done <<< "$tsv"
}

# --- Diff two loaded maps ---
# Receives names of four associative arrays as strings to avoid nameref collision.
run_diff() {
    local -n _an="$1"   # A: name→version
    local -n _ar="$2"   # A: name→repo
    local -n _bn="$3"   # B: name→version
    local -n _br="$4"   # B: name→repo

    local added=() removed=() upgraded=() downgraded=() unchanged=()

    # Check everything in B
    for pkg in "${!_bn[@]}"; do
        local ver_b="${_bn[$pkg]}"
        if [[ -z "${_an[$pkg]+_}" ]]; then
            added+=("$pkg|$ver_b|${_br[$pkg]}")
        else
            local ver_a="${_an[$pkg]}"
            if [[ "$ver_a" == "$ver_b" ]]; then
                unchanged+=("$pkg|$ver_a|${_br[$pkg]}")
            else
                local cmp
                cmp=$(vercmp "$ver_b" "$ver_a" 2>/dev/null || echo 0)
                if [[ "$cmp" -gt 0 ]]; then
                    upgraded+=("$pkg|$ver_a|$ver_b|${_br[$pkg]}")
                else
                    downgraded+=("$pkg|$ver_a|$ver_b|${_br[$pkg]}")
                fi
            fi
        fi
    done

    # Removed: in A but not B
    for pkg in "${!_an[@]}"; do
        if [[ -z "${_bn[$pkg]+_}" ]]; then
            removed+=("$pkg|${_an[$pkg]}|${_ar[$pkg]}")
        fi
    done

    # Sort each category
    IFS=$'\n' added=($(sort <<<"${added[*]}")); unset IFS
    IFS=$'\n' removed=($(sort <<<"${removed[*]}")); unset IFS
    IFS=$'\n' upgraded=($(sort <<<"${upgraded[*]}")); unset IFS
    IFS=$'\n' downgraded=($(sort <<<"${downgraded[*]}")); unset IFS
    IFS=$'\n' unchanged=($(sort <<<"${unchanged[*]}")); unset IFS

    # --- Print results ---
    if ! "$SUMMARY_ONLY"; then

        if [[ ${#added[@]} -gt 0 ]]; then
            section "Added (${#added[@]})"
            printf "  ${BOLD}%-40s %-25s %s${RESET}\n" "PACKAGE" "VERSION" "REPO"
            printf "  %s\n" "$(printf '%.0s─' {1..75})"
            for entry in "${added[@]}"; do
                IFS='|' read -r pkg ver repo <<< "$entry"
                printf "  ${GREEN}+%-40s %-25s %s${RESET}\n" "$pkg" "$ver" "$repo"
            done
        fi

        if [[ ${#removed[@]} -gt 0 ]]; then
            section "Removed (${#removed[@]})"
            printf "  ${BOLD}%-40s %-25s %s${RESET}\n" "PACKAGE" "VERSION" "REPO"
            printf "  %s\n" "$(printf '%.0s─' {1..75})"
            for entry in "${removed[@]}"; do
                IFS='|' read -r pkg ver repo <<< "$entry"
                printf "  ${RED}-%-40s %-25s %s${RESET}\n" "$pkg" "$ver" "$repo"
            done
        fi

        if [[ ${#upgraded[@]} -gt 0 ]]; then
            section "Upgraded (${#upgraded[@]})"
            printf "  ${BOLD}%-40s %-22s %-22s %s${RESET}\n" "PACKAGE" "FROM" "TO" "REPO"
            printf "  %s\n" "$(printf '%.0s─' {1..90})"
            for entry in "${upgraded[@]}"; do
                IFS='|' read -r pkg ver_a ver_b repo <<< "$entry"
                printf "  ${CYAN}↑%-40s %-22s → %-22s %s${RESET}\n" "$pkg" "$ver_a" "$ver_b" "$repo"
            done
        fi

        if [[ ${#downgraded[@]} -gt 0 ]]; then
            section "Downgraded (${#downgraded[@]})"
            printf "  ${BOLD}%-40s %-22s %-22s %s${RESET}\n" "PACKAGE" "FROM" "TO" "REPO"
            printf "  %s\n" "$(printf '%.0s─' {1..90})"
            for entry in "${downgraded[@]}"; do
                IFS='|' read -r pkg ver_a ver_b repo <<< "$entry"
                printf "  ${YELLOW}↓%-40s %-22s → %-22s %s${RESET}\n" "$pkg" "$ver_a" "$ver_b" "$repo"
            done
        fi

        if "$SHOW_UNCHANGED" && [[ ${#unchanged[@]} -gt 0 ]]; then
            section "Unchanged (${#unchanged[@]})"
            printf "  ${BOLD}%-40s %-25s %s${RESET}\n" "PACKAGE" "VERSION" "REPO"
            printf "  %s\n" "$(printf '%.0s─' {1..75})"
            for entry in "${unchanged[@]}"; do
                IFS='|' read -r pkg ver repo <<< "$entry"
                printf "  %-41s %-25s %s\n" "$pkg" "$ver" "$repo"
            done
        fi
    fi

    # --- Summary ---
    section "Summary"
    local total_a=${#_an[@]} total_b=${#_bn[@]}
    printf "  Snapshot A : %d package(s)\n" "$total_a"
    printf "  Snapshot B : %d package(s)\n" "$total_b"
    echo ""
    [[ ${#added[@]}      -gt 0 ]] && printf "  ${GREEN}+ Added      : %d${RESET}\n" "${#added[@]}"
    [[ ${#removed[@]}    -gt 0 ]] && printf "  ${RED}- Removed    : %d${RESET}\n" "${#removed[@]}"
    [[ ${#upgraded[@]}   -gt 0 ]] && printf "  ${CYAN}↑ Upgraded   : %d${RESET}\n" "${#upgraded[@]}"
    [[ ${#downgraded[@]} -gt 0 ]] && printf "  ${YELLOW}↓ Downgraded : %d${RESET}\n" "${#downgraded[@]}"
    printf "  = Unchanged : %d\n" "${#unchanged[@]}"

    local total_changes=$(( ${#added[@]} + ${#removed[@]} + ${#upgraded[@]} + ${#downgraded[@]} ))
    echo ""
    if [[ "$total_changes" -eq 0 ]]; then
        ok "Snapshots are identical."
    else
        info "${total_changes} difference(s) found."
    fi
}

# --- Main ---
main() {
    section "Package List Diff"
    require_cmds pacman vercmp

    parse_args "$@"

    [[ -z "$FILE_A" ]] && fatal "Usage: $(basename "$0") FILE_A [FILE_B]\nRun with --help for options."
    [[ ! -f "$FILE_A" ]] && fatal "File not found: ${FILE_A}"
    [[ -n "$FILE_B" && ! -f "$FILE_B" ]] && fatal "File not found: ${FILE_B}"

    declare -A a_names a_repos b_names b_repos

    info "Loading snapshot A: ${FILE_A}"
    load_pkgs "$(parse_snapshot "$FILE_A")" a_names a_repos

    if [[ -n "$FILE_B" ]]; then
        info "Loading snapshot B: ${FILE_B}"
        load_pkgs "$(parse_snapshot "$FILE_B")" b_names b_repos
    else
        info "Snapshot B: current system"
        load_pkgs "$(get_current_pkgs)" b_names b_repos
    fi

    [[ -n "$FILTER" ]] && info "Filter: ${FILTER} packages only"
    echo ""

    run_diff a_names a_repos b_names b_repos
}

main "$@"
